name: platelet-tracking
channels:
  - conda-forge
  - menpo
dependencies:
  - pandas
  - nd2reader
  - scikit-image
  - trackpy
  - pathlib
  - dask
  - distributed
  - scipy
  - ipython
  - jupyter
  - jupyterlab
# btrack
  - python=3.7
  - pip
  - cvxopt>=1.2.0
  - h5py>=2.10.0
  - matplotlib>=3.1.1
  - numpy>=1.17.3
  - scipy>=1.3.1
  - pip:
    - btrack
    - opencv-python

  